//REGISTRATION
export const HANDLE_CHANGE_NAME = "HANDLE_CHANGE_NAME"
export const HANDLE_CHANGE_EMAIL = "HANDLE_CHANGE_EMAIL"
export const HANDLE_CHANGE_PASS = "HANDLE_CHANGE_PASS"
export const ADD_USER = "ADD_USER"
//LOGIN
export const HANDLE_CHANGE_EMAIL_LOGIN = "HANDLE_CHANGE_EMAIL_LOGIN"
export const HANDLE_CHANGE_PASS_LOGIN = "HANDLE_CHANGE_PASS_LOGIN"
export const CLEAR_LOGIN_FORM = "CLEAR_LOGIN_FORM"

//USER LIST
export const TOGGLE_USER_LIST = "TOGGLE_USER_LIST"

//ADD DEALS
export const HANDLE_CHANGE_TASK = "HANDLE_CHANGE_TASK"
export const ADD_USER_DEALS = "ADD_USER_DEALS"
export const CLEAR_INPUT = "CLEAR_INPUT"

//DEALS 
export const CLEAR_USERS = "CLEAR_USERS"
export const DONE = "DONE"
export const SHOW_ALL_DEALS = "SHOW_ALL_DEALS"
export const SHOW_ACTIVE_DEALS = "SHOW_ACTIVE_DEALS"
export const SHOW_COMPLETED_DEALS = "SHOW_COMPLETED_DEALS"
export const CLEAR_ALL = "CLEAR_ALL"
export const CLEAR_COMPLETED = "CLEAR_COMPLETED"
export const RETURN_ALL = "RETURN_ALL"

