//REGISTRATION
export const HANDLE_CHANGE_NAME = "HANDLE_CHANGE_NAME"
export const HANDLE_CHANGE_EMAIL = "HANDLE_CHANGE_EMAIL"
export const HANDLE_CHANGE_PASS = "HANDLE_CHANGE_PASS"
export const ADD_USER = "ADD_USER"
//LOGIN
export const HANDLE_CHANGE_EMAIL_LOGIN = "HANDLE_CHANGE_EMAIL_LOGIN"
export const HANDLE_CHANGE_PASS_LOGIN = "HANDLE_CHANGE_PASS_LOGIN"
export const CLEAR_LOGIN_FORM = "CLEAR_LOGIN_FORM"

//USER LIST
export const TOGGLE_USER_LIST = "TOGGLE_USER_LIST"

//ADD DEALS
export const HANDLE_CHANGE_TASK = "HANDLE_CHANGE_TASK"
export const ADD_USER_DEALS = "ADD_USER_DEALS"
export const CLEAR_INPUT = "CLEAR_INPUT"
export const DONE_DEAL = "DONE_DEAL"
export const CLEAR_USERS = "CLEAR_USERS"
export const DONE = "DONE"

