//REGISTRATION
export const HANDLE_CHANGE_NAME = "HANDLE_CHANGE_NAME"
export const HANDLE_CHANGE_EMAIL = "HANDLE_CHANGE_EMAIL"
export const HANDLE_CHANGE_PASS = "HANDLE_CHANGE_PASS"
export const ADD_USER = "ADD_USER"
//LOGIN
export const HANDLE_CHANGE_EMAIL_LOGIN = "HANDLE_CHANGE_EMAIL_LOGIN"
export const HANDLE_CHANGE_PASS_LOGIN = "HANDLE_CHANGE_PASS_LOGIN"
export const CLEAR_LOGIN_FORM = "CLEAR_LOGIN_FORM"

//USER LIST
export const TOGGLE_USER_LIST = "TOGGLE_USER_LIST"
